
# Worksheet 0

*   Name: Sirish Tandukar (2329527)
*   Group: L6CG7




# 1. Exercise on Functions

Task - 1:
Create a Python program that converts between different units of measurement.

In [ ]:
def unit_converter(value, source_unit, target_unit):
    """
    Converts a value from one unit to another.

    Parameters:
    value (float)
    source_unit (str)
    target_unit (str)

    Returns:
    float is the converted value.
    """
    #Length conversions
    if source_unit == "m" and target_unit == "ft":
        return value * 3.28084
    elif source_unit == "ft" and target_unit == "m":
        return value / 3.28084
    #Weight conversions
    elif source_unit == "kg" and target_unit == "lbs":
        return value * 2.20462
    elif source_unit == "lbs" and target_unit == "kg":
        return value / 2.20462
    #Volume conversions
    elif source_unit == "L" and target_unit == "gal":
        return value * 0.264172
    elif source_unit == "gal" and target_unit == "L":
        return value / 0.264172
    else:
        raise ValueError("Conversion not supported. Check your units.")

def main():
    #Introduction to the program
    print("Welcome to the Unit Converter!")
    print("Supported conversions include:")
    print("1. Length: meters (m) to feet (ft) and vice versa")
    print("2. Weight: kilograms (kg) to pounds (lbs) and vice versa")
    print("3. Volume: liters (L) to gallons (gal) and vice versa")

    try:
        #Prompt user for conversion category
        category = input("Enter the conversion category (length, weight, volume): ").strip().lower()
        if category not in ["length", "weight", "volume"]:
            print("Error: Unsupported conversion category.")
            return

        #Prompt user for the numeric value to convert
        amount = float(input("Enter the value to convert: "))

        #Prompt user for source and target units based on the category
        if category == "length":
            source_unit = input("Convert from (m/ft): ").strip().lower()
            target_unit = input("Convert to (m/ft): ").strip().lower()
        elif category == "weight":
            source_unit = input("Convert from (kg/lbs): ").strip().lower()
            target_unit = input("Convert to (kg/lbs): ").strip().lower()
        elif category == "volume":
            source_unit = input("Convert from (L/gal): ").strip().lower()
            target_unit = input("Convert to (L/gal): ").strip().lower()

        #Perform the unit conversion
        result = unit_converter(amount, source_unit, target_unit)

        #Display the conversion result
        print(f"{amount} {source_unit} is equal to {result:.2f} {target_unit}.")

    except ValueError as error:
        print(f"Error: {error}")
    except Exception as unexpected_error:
        print(f"An unexpected error occurred: {unexpected_error}")

if __name__ == "__main__":
    main()


Welcome to the Unit Converter!
Supported conversions include:
1. Length: meters (m) to feet (ft) and vice versa
2. Weight: kilograms (kg) to pounds (lbs) and vice versa
3. Volume: liters (L) to gallons (gal) and vice versa
Enter the conversion category (length, weight, volume): weight
Enter the value to convert: 67
Convert from (kg/lbs): kg
Convert to (kg/lbs): lbs
67.0 kg is equal to 147.71 lbs.


Task - 2:
Create a Python program that performs various mathematical operations on a list of numbers.

In [ ]:
def calculate_sum(numbers):
    """
    Calculates the sum of a list of numbers.

    Parameters:
    numbers which is the list of numbers.

    Returns:
    float is the sum of the numbers.
    """
    return sum(numbers)

def calculate_average(numbers):
    """
    Calculates the average of a list of numbers.

    Parameters:
    numbers is the list of numbers.

    Returns:
    float is the average of the numbers.
    """
    return sum(numbers) / len(numbers)

def find_maximum(numbers):
    """
    Finds the maximum value in a list of numbers.

    Parameters:
    numbers is the list of numbers.

    Returns:
    float is the maximum value in the list.
    """
    return max(numbers)

def find_minimum(numbers):
    """
    Finds the minimum value in a list of numbers.

    Parameters:
    numbers is the list of numbers.

    Returns:
    float is the minimum value in the list.
    """
    return min(numbers)

def main():
    print("Mathematical Operations on a List of Numbers")
    print("Choose an operation:")
    print("1. Sum of numbers")
    print("2. Average of numbers")
    print("3. Maximum value")
    print("4. Minimum value")

    try:
        choice = int(input("Enter the number corresponding to the operation (1-4): "))
        if choice not in [1, 2, 3, 4]:
            print("Invalid choice! Please choose a number between 1 and 4.")
            return

        numbers_input = input("Enter a list of numbers separated by spaces: ")
        numbers = [float(x) for x in numbers_input.split()]

        if not numbers:
            print("Error: The list of numbers is empty. Please provide valid input.")
            return
        if choice == 1:
            result = calculate_sum(numbers)
            print(f"The sum of the numbers is: {result:.2f}")
        elif choice == 2:
            result = calculate_average(numbers)
            print(f"The average of the numbers is: {result:.2f}")
        elif choice == 3:
            result = find_maximum(numbers)
            print(f"The maximum value in the list is: {result:.2f}")
        elif choice == 4:
            result = find_minimum(numbers)
            print(f"The minimum value in the list is: {result:.2f}")

    except ValueError:
        print("Error: Invalid input. Please ensure you enter numeric values.")

if __name__ == "__main__":
    main()


Mathematical Operations on a List of Numbers
Choose an operation:
1. Sum of numbers
2. Average of numbers
3. Maximum value
4. Minimum value
Enter the number corresponding to the operation (1-4): 1
Enter a list of numbers separated by spaces: 23 9
The sum of the numbers is: 32.00


# 2. Exercise on List Manipulation

1. Extract Every Other Element:
Write a Python function that extracts every other element from a list, starting from the first element.

In [ ]:
def extract_every_other(lst):
    """
    Extracts every other element from a list, starting from the first element.

    Parameters:
    lst is the input list from which every other element will be extracted.

    Returns:
    A new list containing every other element from the original list.
    """
    return lst[::2]

input_list = [1, 2, 3, 4, 5, 6]
output_list = extract_every_other(input_list)
print("Original list:", input_list)
print("Extracted list (every other element):", output_list)


Original list: [1, 2, 3, 4, 5, 6]
Extracted list (every other element): [1, 3, 5]


2. Slice a Sublist:
Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.

In [ ]:
def get_sublist(lst, start, end):
    """
    The function returns a sublist from the given list, starting from the specified index and ending at the specified index (inclusive).

    Parameters:
    lst (list): The original list.
    start (int): The starting index for the sublist.
    end (int): The ending index for the sublist.

    Returns:
    list in the sublist from start to end (inclusive).
    """
    return lst[start:end+1]

input_list = [1, 2, 3, 4, 5, 6]
start_index = 2
end_index = 4
output_sublist = get_sublist(input_list, start_index, end_index)

print("Original list:", input_list)
print(f"Sublist from index {start_index} to {end_index} (inclusive):", output_sublist)


Original list: [1, 2, 3, 4, 5, 6]
Sublist from index 2 to 4 (inclusive): [3, 4, 5]


3. Reverse a List Using Slicing:
Write a Python function that reverses a list using slicing.

In [ ]:
def reverse_list(lst):
    """
    The function reverses a list using slicing.

    Parameters:
    lst is the list to be reversed.

    Returns:
    list is the reversed list.
    """
    return lst[::-1]

input_list = [1, 2, 3, 4, 5]
reversed_list = reverse_list(input_list)

print("Original list:", input_list)
print("Reversed list:", reversed_list)


Original list: [1, 2, 3, 4, 5]
Reversed list: [5, 4, 3, 2, 1]


4. Remove the First and Last Elements:
Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.

In [ ]:
def remove_first_last(lst):
    """
    Removes the first and last elements of a list and returns the resulting sublist.

    Parameters:
    lst is the input list from which the first and last elements will be removed.

    Returns:
    list is a new list without the first and last elements.
    """
    return lst[1:-1]
input_list = [1, 2, 3, 4, 5]
resulting_list = remove_first_last(input_list)

print("Original list:", input_list)
print("List after removing first and last elements:", resulting_list)


Original list: [1, 2, 3, 4, 5]
List after removing first and last elements: [2, 3, 4]


5. Get the First n Elements:
Write a Python function that extracts the first n elements from a list.

In [ ]:
def get_first_n(lst, n):
    """
    Extracts the first n elements from a list.

    Parameters:
    lst is the input list from which the elements will be extracted.
    The number of elements to extract.

    Returns:
    list is a new list containing the first n elements of the input list.
    """
    return lst[:n]

input_list = [1, 2, 3, 4, 5]
n = 3
output_list = get_first_n(input_list, n)

print("Original list:", input_list)
print(f"The first {n} elements of the list are:", output_list)


Original list: [1, 2, 3, 4, 5]
The first 3 elements of the list are: [1, 2, 3]


6. Extract Elements from the End:
Write a Python function that extracts the last n elements of a list using slicing.

In [ ]:
def get_last_n(lst, n):
    """
    Extracts the last n elements from a list.

    Parameters:
    lst is the input list from which the elements will be extracted.
    n is the number of elements to extract from the end.

    Returns:
    list is a new list containing the last n elements of the input list.
    """
    return lst[-n:]

input_list = [1, 2, 3, 4, 5]
n = 2
output_list = get_last_n(input_list, n)

print("Original list:", input_list)
print(f"The last {n} elements of the list are:", output_list)


Original list: [1, 2, 3, 4, 5]
The last 2 elements of the list are: [4, 5]


7. Extract Elements in Reverse Order:
Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.

In [ ]:
def reverse_skip(lst):
    """
    Extracts elements in reverse order starting from the second-to-last element and skipping one element in between.

    Parameters:
    lst is the input list.

    Returns:
    list is a new list containing every second element starting from the second-to-last, moving backward.
    """
    return lst[-2::-2]

input_list = [1, 2, 3, 4, 5, 6]
output_list = reverse_skip(input_list)

print("Original list:", input_list)
print("Extracted elements in reverse order (skipping one):", output_list)


Original list: [1, 2, 3, 4, 5, 6]
Extracted elements in reverse order (skipping one): [5, 3, 1]


# 3. Exercise on Nested List

1. Flatten a Nested List:
Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.

In [ ]:
def flatten(lst):
    """
    Flattens a nested list into a single list.

    Parameters:
    lst is the nested list to be flattened.

    Returns:
    list is a flattened version of the input list.
    """
    flattened_list = []
    for sublist in lst:
        flattened_list.extend(sublist)
    return flattened_list

nested_list = [[1, 2], [3, 4], [5]]
flattened_list = flatten(nested_list)

print("Original nested list:", nested_list)
print("Flattened list:", flattened_list)


Original nested list: [[1, 2], [3, 4], [5]]
Flattened list: [1, 2, 3, 4, 5]


2. Accessing Nested List Elements:
Write a Python function that extracts a specific element from a nested list given its indices.

In [ ]:
def access_nested_element(lst, indices):
    """
    Extracts a specific element from a nested list given its indices.

    Parameters:
    lst (list) is the nested list.
    indices (list of int) is a list of indices representing the position of the desired element.

    Returns:
    The element at the specified position in the nested list.
    """
    element = lst
    for index in indices:
        element = element[index]
    return element

nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]
result = access_nested_element(nested_list, indices)

print("Nested list:", nested_list)
print("Indices:", indices)
print("Element at the specified position:", result)


Nested list: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Indices: [1, 2]
Element at the specified position: 6


3. Sum of All Elements in a Nested List:
Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

In [ ]:
def sum_nested(lst):
    """
    Calculates the sum of all the numbers in a nested list, regardless of depth.

    Parameters:
    lst (list) is the nested list containing numbers.

    Returns:
    The sum of all numbers in the nested list.
    """
    total = 0
    for element in lst:
        if isinstance(element, list):
            total += sum_nested(element)
        else:
            total += element
    return total

nested_list = [[1, 2], [3, [4, 5]], 6]
result = sum_nested(nested_list)

print("Nested list:", nested_list)
print("Sum of all elements:", result)


Nested list: [[1, 2], [3, [4, 5]], 6]
Sum of all elements: 21


4. Remove Specific Element from a Nested List:
Write a Python function that removes all occurrences of a specific element from a nested list.


In [ ]:
def remove_element(lst, elem):
    """
    Removes all occurrences of a specific element from a nested list.

    Parameters:
    lst (list) is the nested list.
    elem (Any) is the element to be removed.

    Returns:
    list is the modified list with the specified element removed.
    """
    modified_list = []
    for sublist in lst:
        if isinstance(sublist, list):
            modified_list.append(remove_element(sublist, elem))
        else:
            if sublist != elem:
                modified_list.append(sublist)
    return modified_list

nested_list = [[1, 2], [3, 2], [4, 5]]
element_to_remove = 2
result = remove_element(nested_list, element_to_remove)

print("Original nested list:", nested_list)
print(f"Nested list after removing {element_to_remove}:", result)


Original nested list: [[1, 2], [3, 2], [4, 5]]
Nested list after removing 2: [[1], [3], [4, 5]]


5. Find the Maximum Element in a Nested List:
Write a Python function that finds the maximum element in a nested list (regardless of depth).

In [ ]:
def find_max(lst):
    """
    Finds the maximum element in a nested list, regardless of depth.

    Parameters:
    lst (list) is the nested list containing elements.

    Returns:
    int/float is the maximum element in the nested list.
    """
    max_element = float('-inf')
    for element in lst:
        if isinstance(element, list):
            max_element = max(max_element, find_max(element))
        else:
            max_element = max(max_element, element)
    return max_element

nested_list = [[1, 2], [3, [4, 5]], 6]
result = find_max(nested_list)

print("Nested list:", nested_list)
print("Maximum element:", result)


Nested list: [[1, 2], [3, [4, 5]], 6]
Maximum element: 6


6. Count Occurrences of an Element in a Nested List:
Write a Python function that counts how many times a specific element appears in a nested list.

In [ ]:
def count_occurrences(lst, elem):
    """
    Counts how many times a specific element appears in a nested list.

    Parameters:
    lst (list) is the nested list to search.
    elem (Any) is the element to count.

    Returns:
    The count of occurrences of the element in the nested list.
    """
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        else:
            if item == elem:
                count += 1
    return count

nested_list = [[1, 2], [2, 3], [2, 4]]
element_to_count = 2
result = count_occurrences(nested_list, element_to_count)

print("Nested list:", nested_list)
print(f"Element {element_to_count} occurs {result} times.")


Nested list: [[1, 2], [2, 3], [2, 4]]
Element 2 occurs 3 times.


7. Flatten a List of Lists of Lists:
Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

In [ ]:
def deep_flatten(lst):
    """
    Flattens a deeply nested list into a single list.

    Parameters:
    lst (list) is the deeply nested list to flatten.

    Returns:
    A single flattened list containing all the elements of the input list.
    """
    flattened_list = []
    for element in lst:
        if isinstance(element, list):

            flattened_list.extend(deep_flatten(element))
        else:
            flattened_list.append(element)
    return flattened_list

nested_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
result = deep_flatten(nested_list)

print("Original nested list:", nested_list)
print("Flattened list:", result)


Original nested list: [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
Flattened list: [1, 2, 3, 4, 5, 6, 7, 8]


8. Nested List Average:
Write a Python function that calculates the average of all elements in a nested list.

In [ ]:
def average_nested(lst):
    """
    Calculates the average of all elements in a nested list.

    Parameters:
    lst (list) is the nested list containing numerical elements.

    Returns:
    float is the average of all elements in the nested list.
    """
    def flatten_and_sum(lst):
        """
        Flattens a nested list and calculates the sum and count of all elements.

        Parameters:
        lst (list) is the nested list to process.

        Returns:
        tuple is a tuple containing the sum of all elements and the count of elements.
        """
        total_sum = 0
        count = 0
        for element in lst:
            if isinstance(element, list):
                sub_sum, sub_count = flatten_and_sum(element)
                total_sum += sub_sum
                count += sub_count
            else:
                total_sum += element
                count += 1
        return total_sum, count

    #flatten the list to get the total sum and count
    total_sum, count = flatten_and_sum(lst)
    return total_sum / count if count != 0 else 0

nested_list = [[1, 2], [3, 4], [5, 6]]
result = average_nested(nested_list)

print("Nested list:", nested_list)
print("Average of all elements:", result)


Nested list: [[1, 2], [3, 4], [5, 6]]
Average of all elements: 3.5


# 4. Basic Vector and Matrix Operation with Numpy.

Problem - 1: Array Creation

In [ ]:
import numpy as np
#1: Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("Empty array (2x2):\n", empty_array)

#2: Initialize an all-one array with size 4x2
ones_array = np.ones((4, 2))
print("\nAll-ones array (4x2):\n", ones_array)

#3: Return a new array of given shape and type, filled with a fill value
fill_value = 7
filled_array = np.full((3, 3), fill_value)
print("\nArray filled with value", fill_value, ":\n", filled_array)

#4: Return a new array of zeros with same shape and type as a given array
reference_array = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_array = np.zeros_like(reference_array)
print("\nArray of zeros with the same shape and type as reference array:\n", zeros_like_array)

#5: Return a new array of ones with same shape and type as a given array
ones_like_array = np.ones_like(reference_array)
print("\nArray of ones with the same shape and type as reference array:\n", ones_like_array)

#6: Convert an existing list to a NumPy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\nConverted NumPy array from new_list:\n", numpy_array)


Empty array (2x2):
 [[3.22844301e-316 0.00000000e+000]
 [0.00000000e+000 1.16304933e+214]]

All-ones array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Array filled with value 7 :
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Array of zeros with the same shape and type as reference array:
 [[0 0 0]
 [0 0 0]]

Array of ones with the same shape and type as reference array:
 [[1 1 1]
 [1 1 1]]

Converted NumPy array from new_list:
 [1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing

In [ ]:
import numpy as np

#1: Create an array with values ranging from 10 to 49
array_10_to_49 = np.arange(10, 50)
print("Array with values ranging from 10 to 49:\n", array_10_to_49)

#2: Create a 3x3 matrix with values ranging from 0 to 8
matrix_0_to_8 = np.arange(9).reshape(3, 3)
print("\n3x3 Matrix with values from 0 to 8:\n", matrix_0_to_8)

#3: Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("\n3x3 Identity Matrix:\n", identity_matrix)

#4: Create a random array of size 30 and find the mean
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\nRandom array of size 30:\n", random_array)
print("Mean of the array:", mean_value)

#5: Create a 10x10 array with random values and find the min and max
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("\n10x10 Array with random values:\n", random_10x10)
print("Minimum value:", min_value)
print("Maximum value:", max_value)

#6: Create a zero array of size 10 and replace 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1
print("\nZero array with 5th element replaced by 1:\n", zero_array)

#7: Reverse an array [1, 2, 0, 0, 4, 0]
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_array = arr[::-1]
print("\nReversed array:\n", reversed_array)

#8: Create a 2D array with 1 on the border and 0 inside
border_array = np.ones((6, 6))
border_array[1:-1, 1:-1] = 0
print("\n2D Array with border of 1 and inside 0:\n", border_array)

#9: Create an 8x8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n8x8 Checkerboard Pattern:\n", checkerboard)


Array with values ranging from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix with values from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random array of size 30:
 [0.74072474 0.62588933 0.31289956 0.30324031 0.23670024 0.52761616
 0.13642736 0.60497534 0.44251472 0.36898918 0.28247489 0.31261924
 0.90667892 0.93068095 0.92028499 0.07132413 0.71600985 0.28724413
 0.56370525 0.86221761 0.30117232 0.15919072 0.8512503  0.68874303
 0.75980247 0.22425474 0.47130558 0.4772368  0.30525205 0.75418181]
Mean of the array: 0.504853557283383

10x10 Array with random values:
 [[0.6948934  0.04441311 0.57742123 0.56605872 0.25288577 0.18604591
  0.07470038 0.51694477 0.65672935 0.57416073]
 [0.8396701  0.93274103 0.11453205 0.37727352 0.59924841 0.66233318
  0.94872406 0.76940143 0.40258039 0.96539534]
 [0.03907071 0.66488663 0.70080038 0.2960713 

Problem - 3: Array Operations

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

#1: Add the two arrays (x and y)
add_xy = x + y
print("Addition of x and y:\n", add_xy)

#2: Subtract the two arrays (x and y)
subtract_xy = x - y
print("\nSubtraction of x and y:\n", subtract_xy)

#3: Multiply the array (x) with an integer of your choice (e.g., 2)
multiply_x = x * 2
print("\nMultiplication of x with 2:\n", multiply_x)

#4: Find the square of each element of the array (x)
square_x = np.square(x)
print("\nSquare of each element in x:\n", square_x)

#5: Find the dot products
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("\nDot product of v and w:", dot_vw)
print("Dot product of x and v:\n", dot_xv)
print("Dot product of x and y:\n", dot_xy)

#6: Concatenate x and y along rows; Concatenate v and w along columns
concat_xy_rows = np.concatenate((x, y), axis=0)
concat_vw_columns = np.vstack((v, w))
print("\nConcatenate x and y along rows:\n", concat_xy_rows)
print("Concatenate v and w along columns:\n", concat_vw_columns)

#7: Concatenate x and v
try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("\nConcatenate x and v along rows:\n", concat_xv)
except ValueError as e:
    print("\nError when concatenating x and v:", e)
    print("Explanation: The dimensions of x (2x2) and v (1x2) are incompatible for concatenation along rows. ")

Addition of x and y:
 [[ 6  8]
 [10 13]]

Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]

Multiplication of x with 2:
 [[ 2  4]
 [ 6 10]]

Square of each element in x:
 [[ 1  4]
 [ 9 25]]

Dot product of v and w: 219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]

Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along columns:
 [[ 9 10]
 [11 12]]

Error when concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: The dimensions of x (2x2) and v (1x2) are incompatible for concatenation along rows. 


Problem - 4: Matrix Operations

Part 1

In [ ]:
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

#1: Prove A * A^-1 = I
A_inv = np.linalg.inv(A)
identity_matrix = np.dot(A, A_inv)
print("A * A^-1 (Identity Matrix):\n", np.round(identity_matrix, decimals=6))

#2: Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nMatrix AB:\n", AB)
print("\nMatrix BA:\n", BA)
print("\nAre AB and BA equal?", np.array_equal(AB, BA))

#3: Prove (AB)^T = B^T A^T
AB_T = np.transpose(AB)
BT_AT = np.dot(np.transpose(B), np.transpose(A))
print("\n(AB)^T:\n", AB_T)
print("\nB^T * A^T:\n", BT_AT)
print("\nIs (AB)^T equal to B^T * A^T?", np.array_equal(np.round(AB_T, decimals=6), np.round(BT_AT, decimals=6)))


A * A^-1 (Identity Matrix):
 [[1. 0.]
 [0. 1.]]

Matrix AB:
 [[23 13]
 [51 29]]

Matrix BA:
 [[36 44]
 [13 16]]

Are AB and BA equal? False

(AB)^T:
 [[23 51]
 [13 29]]

B^T * A^T:
 [[23 51]
 [13 29]]

Is (AB)^T equal to B^T * A^T? True


Part 2

In [ ]:
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])

#X using the inverse method
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
print("\nSolution for the system of equations (X):\n", X)



Solution for the system of equations (X):
 [ 2.  1. -2.]


# 5. Experiment: How Fast is Numpy?

1. Element-wise Addition

In [ ]:
import time
list1 = [i for i in range(1, 1000001)]
list2 = [i for i in range(1000001, 2000001)]

start_time = time.time()
result = [list1[i] + list2[i] for i in range(1000000)]
end_time = time.time()
print(f"Time taken for element-wise addition: {end_time - start_time} seconds")

Time taken for element-wise addition: 0.08252382278442383 seconds


In [ ]:
import numpy as np
import time

array1 = np.arange(1, 1000001)
array2 = np.arange(1000001, 2000001)

start_time = time.time()
result = array1 + array2
end_time = time.time()
print(f"Time taken for element-wise addition with NumPy: {end_time - start_time} seconds")

Time taken for element-wise addition with NumPy: 0.006112098693847656 seconds


2. Element-wise Multiplication

In [ ]:
import time
import numpy as np

size = 1_000_000

list1 = [i for i in range(size)]
list2 = [i for i in range(size)]

start_time = time.time()
result_list = [list1[i] * list2[i] for i in range(size)]
end_time = time.time()
print(f"Time taken using Python lists: {end_time - start_time:.6f} seconds")

array1 = np.arange(size)
array2 = np.arange(size)

result_array = array1 * array2
end_time = time.time()
print(f"Time taken using NumPy arrays: {end_time - start_time:.6f} seconds")


Time taken using Python lists: 0.084936 seconds
Time taken using NumPy arrays: 0.007907 seconds


3. Dot Product

In [ ]:
import time
import numpy as np

size = 1_000_000
list1 = [i for i in range(size)]
list2 = [i for i in range(size)]

start_time = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(size))
end_time = time.time()
print(f"Time taken using Python lists: {end_time - start_time:.6f} seconds")

array1 = np.arange(size)
array2 = np.arange(size)

start_time = time.time()
dot_product_array = np.dot(array1, array2)
end_time = time.time()
print(f"Time taken using NumPy arrays: {end_time - start_time:.6f} seconds")


Time taken using Python lists: 0.247972 seconds
Time taken using NumPy arrays: 0.001973 seconds


4. Matrix Multiplication

In [ ]:
import time
def matrix_multiply(A, B):
    result = [[0] * len(B[0]) for _ in range(len(A))]
    #matrix multiplication
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                result[i][j] += A[i][k] * B[k][j]
    return result

matrix_A = [[1] * 1000 for _ in range(1000)]
matrix_B = [[1] * 1000 for _ in range(1000)]

start_time = time.time()
#matrix multiplication
result_matrix = matrix_multiply(matrix_A, matrix_B)
end_time = time.time()
print(f"Time taken for matrix multiplication using Python lists: {end_time - start_time} seconds")


Time taken for matrix multiplication using Python lists: 129.408842086792 seconds


In [ ]:
import numpy as np
import time

matrix_A = np.ones((1000, 1000))
matrix_B = np.ones((1000, 1000))

start_time = time.time()

#matrix multiplication using NumPy
result_matrix = np.dot(matrix_A, matrix_B)
end_time = time.time()
print(f"Time taken for matrix multiplication using NumPy: {end_time - start_time} seconds")


Time taken for matrix multiplication using NumPy: 0.09435558319091797 seconds
